/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package org.apmem.tools.layouts;

public final class R {
	public static final class attr {
		public static final int debugDraw = 0x7f010003;
		public static final int horizontalSpacing = 0x7f010000;
		public static final int layout_horizontalSpacing = 0x7f010005;
		public static final int layout_newLine = 0x7f010004;
		public static final int layout_verticalSpacing = 0x7f010006;
		public static final int orientation = 0x7f010002;
		public static final int verticalSpacing = 0x7f010001;
	}
	public static final class id {
		public static final int horizontal = 0x7f040000;
		public static final int vertical = 0x7f040001;
	}
	public static final class styleable {
		public static final int[] FlowLayout = { 0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003 };
		public static final int[] FlowLayout_LayoutParams = { 0x7f010004, 0x7f010005, 0x7f010006 };
		public static final int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
		public static final int FlowLayout_LayoutParams_layout_newLine = 0;
		public static final int FlowLayout_LayoutParams_layout_verticalSpacing = 2;
		public static final int FlowLayout_debugDraw = 3;
		public static final int FlowLayout_horizontalSpacing = 0;
		public static final int FlowLayout_orientation = 2;
		public static final int FlowLayout_verticalSpacing = 1;
	}
}
