/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.apmem.tools.example;

public final class R {
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int debugDraw=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int horizontalSpacing=0x7f010000;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_horizontalSpacing=0x7f010005;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_newLine=0x7f010004;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int layout_verticalSpacing=0x7f010006;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>horizontal</code></td><td>0</td><td></td></tr>
<tr><td><code>vertical</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int orientation=0x7f010002;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int verticalSpacing=0x7f010001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int horizontal=0x7f040000;
        public static final int vertical=0x7f040001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int button_horizontalSpacing=0x7f050002;
        public static final int button_longTest=0x7f050004;
        public static final int button_newLine=0x7f050005;
        public static final int button_test=0x7f050001;
        public static final int button_verticalSpacing=0x7f050003;
    }
    public static final class styleable {
        /** Attributes that can be used with a FlowLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FlowLayout_debugDraw org.apmem.tools.example:debugDraw}</code></td><td></td></tr>
           <tr><td><code>{@link #FlowLayout_horizontalSpacing org.apmem.tools.example:horizontalSpacing}</code></td><td></td></tr>
           <tr><td><code>{@link #FlowLayout_orientation org.apmem.tools.example:orientation}</code></td><td></td></tr>
           <tr><td><code>{@link #FlowLayout_verticalSpacing org.apmem.tools.example:verticalSpacing}</code></td><td></td></tr>
           </table>
           @see #FlowLayout_debugDraw
           @see #FlowLayout_horizontalSpacing
           @see #FlowLayout_orientation
           @see #FlowLayout_verticalSpacing
         */
        public static final int[] FlowLayout = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#debugDraw}
          attribute's value can be found in the {@link #FlowLayout} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.apmem.tools.example:debugDraw
        */
        public static final int FlowLayout_debugDraw = 3;
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#horizontalSpacing}
          attribute's value can be found in the {@link #FlowLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.apmem.tools.example:horizontalSpacing
        */
        public static final int FlowLayout_horizontalSpacing = 0;
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#orientation}
          attribute's value can be found in the {@link #FlowLayout} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>horizontal</code></td><td>0</td><td></td></tr>
<tr><td><code>vertical</code></td><td>1</td><td></td></tr>
</table>
          @attr name org.apmem.tools.example:orientation
        */
        public static final int FlowLayout_orientation = 2;
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#verticalSpacing}
          attribute's value can be found in the {@link #FlowLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.apmem.tools.example:verticalSpacing
        */
        public static final int FlowLayout_verticalSpacing = 1;
        /** Attributes that can be used with a FlowLayout_LayoutParams.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FlowLayout_LayoutParams_layout_horizontalSpacing org.apmem.tools.example:layout_horizontalSpacing}</code></td><td></td></tr>
           <tr><td><code>{@link #FlowLayout_LayoutParams_layout_newLine org.apmem.tools.example:layout_newLine}</code></td><td></td></tr>
           <tr><td><code>{@link #FlowLayout_LayoutParams_layout_verticalSpacing org.apmem.tools.example:layout_verticalSpacing}</code></td><td></td></tr>
           </table>
           @see #FlowLayout_LayoutParams_layout_horizontalSpacing
           @see #FlowLayout_LayoutParams_layout_newLine
           @see #FlowLayout_LayoutParams_layout_verticalSpacing
         */
        public static final int[] FlowLayout_LayoutParams = {
            0x7f010004, 0x7f010005, 0x7f010006
        };
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#layout_horizontalSpacing}
          attribute's value can be found in the {@link #FlowLayout_LayoutParams} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.apmem.tools.example:layout_horizontalSpacing
        */
        public static final int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#layout_newLine}
          attribute's value can be found in the {@link #FlowLayout_LayoutParams} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.apmem.tools.example:layout_newLine
        */
        public static final int FlowLayout_LayoutParams_layout_newLine = 0;
        /**
          <p>This symbol is the offset where the {@link org.apmem.tools.example.R.attr#layout_verticalSpacing}
          attribute's value can be found in the {@link #FlowLayout_LayoutParams} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.apmem.tools.example:layout_verticalSpacing
        */
        public static final int FlowLayout_LayoutParams_layout_verticalSpacing = 2;
    };
}
